# Copyright© 2023-2024 Quantum Interface (quantuminterface@ipe.kit.edu)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[build-system]
requires = ["hatchling>=1.25", "hatch-vcs>=0.4"]
build-backend = "hatchling.build"


[project]
name = "crudo"
authors = [
    { name = "Quantum Interface", email = "quantuminterface@ipe.kit.edu" },
]
description = "Library for high-level user control of the QiController for cryogenic detector readout"
readme = "README.md"

dependencies = [
    "numpy>=1.24.2",
    "scipy>=1.10.1",
    "matplotlib>=3.7.1",
    "bitarray>=2.7.3",
    "cirque>=1.0",
    "setuptools>=68.2.2",
    "pandas>=2.0.2",
    "deprecated>=1.2.16",
    "lmfit>=1.3.3",
]
requires-python = ">= 3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]
dynamic = ["version"]

[project.urls]
Repository = "https://gitlab.kit.edu/kit/ipe-sdr/software/crudo"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/crudo/_version.py"

[dependency-groups]
dev = [
    "nb-clean>=4.0.1",
]
