import numpy as np
from matplotlib import pyplot as plt
from scipy import signal
from scipy import optimize
from deprecated import deprecated


from . import ipe_scipy

# TODO: Complex data handling


def plot_sync_flag(
    raw_data, ramp_length, current_sync_delay=0, internal_delay=3, figure=None
):
    """
    Function to plot the sync flag in the flux ramp.
    The sync flag is used to separate the separate ramp periods from another.
    The LSB of the data is used as the sync flag.

    Note:
        The sync flag is generated by the ramp generation module and used as an input of the fluxramp demodulation module.
        Make sure that :func:`~firmware_modules.fluxrampdemod.FluxrampDemod.SetActSyncBypass` is activated.

    Args:
        raw_data: Raw data after channelizer of one channel
        ramp_length: Length of the flux ramp in samples
        current_sync_delay: Current delay of the demodulation defaults to 0
        ramp_count: Amount of ramps in data, defaults to 1
        internal_delay: Processing specific parameter, window module implies 3 cycles delay
    """
    # Get LSB as sync flag, nonezero gets indices of none zero values
    # Add intrinsic delay to first sync
    sync_flags = np.nonzero(np.real(raw_data) % 2)[0] + internal_delay

    data = np.abs(raw_data)

    # Scale Plot
    ymin, ymax = np.amin(data), np.amax(data)

    try:
        ctr = int(sync_flags[0] - current_sync_delay)
    except IndexError:
        ctr = 0
        print("Error: No Flag Found")

    if figure is None:
        _, ax = plt.figure()
    else:
        ax = figure

    # Plot ramp including sync flag
    ax.plot(np.arange(len(data)) - ctr, data)
    for idx in sync_flags:
        ax.plot([idx - ctr, idx - ctr], [ymin, ymax], color="r")

    # Plot discarded region

    # ax.title(
    #    f"current Delay: {current_sync_delay} samples, ramp length: {ramp_length}"
    # )
    ax.grid()


def cut_signal(
    data, ramp_sample_count, accumulation_range=None, plot=True, verbose=False
):

    sliced_traces = slice_at_sync(data, ramp_sample_count, add_sync_latency=1)

    if len(sliced_traces) == 0:
        return None
    elif verbose:
        print(f"Number of sliced traces: {len(sliced_traces)}")

    if accumulation_range != None:
        if len(sliced_traces.shape) == 2:
            sliced_traces_trimmed = sliced_traces[0][
                accumulation_range[0] : accumulation_range[1]
            ]
        else:
            sliced_traces_trimmed = sliced_traces[
                accumulation_range[0] : accumulation_range[1]
            ]
    else:
        sliced_traces_trimmed = sliced_traces

    # else:
    #    if len(sliced_traces.shape) == 2:
    #        sliced_traces_trimmed = sliced_traces[0]
    #    else:
    #        sliced_traces_trimmed = sliced_traces

    if type(plot) is bool:
        _, ax = plt.subplots(2, 1)
        t_space = np.arange(sliced_traces.shape[-1])
        if len(sliced_traces.shape) == 2:
            ax[0].plot(np.abs(sliced_traces[0]))
        else:
            ax[0].plot(np.abs(sliced_traces))
        # ax[0].set_xlabel("time in µs")
        ax[0].set_xlabel("Fluxramp sample")
        ax[0].set_ylabel("amplitude in ADU")

        if accumulation_range != None:
            ax[0].axvline(accumulation_range[0], color="red")
            ax[0].axvline(accumulation_range[1], color="red")

        ax[1].plot(np.abs(sliced_traces_trimmed))
        # ax[0].set_xlabel("time in µs")
        ax[1].set_xlabel("Fluxramp sample")
        ax[1].set_ylabel("amplitude in ADU")
        plt.show()
    else:
        if len(sliced_traces.shape) == 2:
            x = range(len(sliced_traces[0]))
            plot.plot(x, np.abs(sliced_traces[0]))
        else:
            x = range(len(sliced_traces))
            plot.plot(np.abs(sliced_traces))
        # ax[0].set_xlabel("time in µs")
        plot.set_xlabel("Fluxramp sample")
        plot.set_ylabel("amplitude in ADU")

        if accumulation_range != None:
            plot.axvline(accumulation_range[0], color="red")
            plot.axvline(accumulation_range[1], color="red")
            plot.axvspan(0, accumulation_range[0], color="gray", alpha=0.5)
            plot.axvspan(
                accumulation_range[1], ramp_sample_count - 1, color="gray", alpha=0.5
            )

    return sliced_traces_trimmed


# Sine fit
def sine_func(x, a, b, c, d):
    return a * np.sin(b * x + c) + d


def find_modulation_freq(data, sample_rate, plot=False):
    fftax = None
    fitax = None
    if type(plot) is list:
        fftax = plot[0]
        fitax = plot[1]
    elif plot is not None:
        fftax = plot
        fitax = plot

    frequency_estimate, _ = signal_fft(
        data, sample_rate=sample_rate, height=0.001, window="rectangular", plot=fftax
    )

    phase_est = phase_estimate(data)

    modulation_frequency, modulation_offset = signal_fit(
        data, sample_rate, frequency_estimate, phase_est, fitax
    )

    return modulation_frequency, modulation_offset


def signal_fit(
    data,
    sample_rate,
    frequency_estimate=None,
    phase_estimate=None,
    plot=False,
    verbose=False,
):
    window_length = len(data)
    if frequency_estimate == None:
        frequency_estimate = sample_rate / 32
    frequency_estimate_normed = frequency_estimate / sample_rate * (2 * np.pi)
    p0 = [
        (max(abs(data)) - min(abs(data))) / 2,
        abs(frequency_estimate_normed),
        phase_estimate,
        np.mean(abs(data)),
    ]
    # TODO without phase needs negative freqs. gradient search does not work!
    bounds = [
        [0, 0, 0, min(abs(data))],
        [max(abs(data)), sample_rate / 4, 2 * np.pi, max(abs(data))],
    ]
    if verbose:
        print(f"Guess: {p0}")

    params, params_cov = optimize.curve_fit(
        lambda x, pha: sine_func(x, p0[0], p0[1], pha, p0[-1]),  # Fit phase first
        np.linspace(0, window_length - 1, window_length),
        np.abs(data),
        p0=p0[2],
        bounds=[0, 2 * np.pi],
        maxfev=5e4,
    )
    p0[2] = params[0]

    params, params_cov = optimize.curve_fit(
        sine_func,
        np.linspace(0, window_length - 1, window_length),
        np.abs(data),
        p0=p0,
        bounds=bounds,
        maxfev=5e4,
    )
    if verbose:
        print(f"Params: {params}")
    fitted_frequency = (params[1] / (2 * np.pi)) * sample_rate
    if plot:
        if type(plot) is not bool:
            plt.sca(plot)
        plt.plot(data, ".", label="data")
        plt.plot(
            np.linspace(0, window_length - 1, window_length * 10),
            sine_func(
                np.linspace(0, window_length - 1, window_length * 10),
                *params,
            ),
            label=f"Sine fit, f = {fitted_frequency/1e3:3.3f} kHz",
        )
        plt.plot(
            np.linspace(0, window_length - 1, window_length * 10),
            sine_func(
                np.linspace(0, window_length - 1, window_length * 10),
                *p0,
            ),
            label=f"Guess f = {(p0[1] / (2 * np.pi)) * sample_rate/1e3:3.3f} kHz",
        )
        plt.legend()
        if type(plot) is bool:
            plt.show()

    return fitted_frequency, params[3]


def phase_estimate(data):
    pkx, _ = signal.find_peaks(data, height=np.median(data))
    if len(pkx) > 1:
        return (-(0.5 + pkx[0] / (pkx[1] - pkx[0])) * np.pi) % np.pi
    # TODO Percentile?
    # TODO Always use the latter?
    temp = np.abs(data - np.median(data))
    pkx, _ = signal.find_peaks(temp, height=np.median(temp))
    if len(pkx) > 1:
        return (-(0.25 + pkx[0] / (pkx[1] - pkx[0])) * np.pi) % np.pi
    return 0 if abs(data[1]) - abs(data[0]) > 0 else np.pi


def signal_fft(
    data,
    sample_rate,
    height=None,
    window="rectangular",
    current_conf=None,
    flim=(0, None),
    plot=True,
):
    """
    Compute the modulation frequencies from the FFT of raw traces.
    For multiple traces (passed as numpy 2d-array) the FFT spectra are averaged.

    Args:
        sliced_traces: input data
        sample_rate (int): sample_rate of the input data
        height (float): threshold of the frequeny to be considered as modulation
        window (String): Window to be used within the FFT
        current_conf: ??
        flim: ??
    """
    # TODO Why DSB?
    # TODO if not working, try padding/repeating
    # TODO if not working, count peaks/transitions
    f_space, p_spec = signal.periodogram(data, sample_rate, window, scaling="density")
    # FFT is averaged if 2d-array is passed

    if plot:
        if type(plot) is bool:
            plt.figure(figsize=(10, 7))
        else:
            plt.sca(plot)
        plt.plot(1e-6 * f_space, p_spec)
        if height is None:
            print("Pass a height to specify the peak threshold")
        else:
            plt.semilogy(1e-6 * f_space, height * np.ones(len(f_space)))
        plt.xlim(flim)
        plt.xlabel("frequency in MHz")
        plt.ylabel("power spectral density")

        # if not current_conf is None:
        #    plot_frequency_config(current_conf, ax[1])
        if type(plot) is bool:
            plt.show()

    peak_indices, _ = signal.find_peaks(p_spec, height=height)
    peak_freq = [f_space[idx] for idx in peak_indices]
    peak_ampl = p_spec[5]

    # print(f"Peak freq: {peak_freq[0]}, index {peak_indices[0]}")
    peak_freq = sorted(np.abs(peak_freq))
    if peak_freq[0] < 1e3:
        del peak_freq[0]
    if len(peak_freq) == 0:
        peak_freq = None
    else:
        peak_freq = peak_freq[0]
    return peak_freq, peak_ampl


@deprecated(version="0.0.2", reason="Calibrate frequency by using signal_fit method")
def find_modulation_frequencies(
    sliced_traces,
    sample_rate,
    height=None,
    window="rectangular",
    current_conf=None,
    accumulation_range=None,
    flim=(0, None),
    plot=True,
):
    """
    Compute the modulation frequencies from the FFT of raw traces.
    For multiple traces (passed as numpy 2d-array) the FFT spectra are averaged.

    Args:
        sliced_traces: input data
        sample_rate (int): sample_rate of the input data
        height (float): threshold of the frequeny to be considered as modulation
        window (String): Window to be used within the FFT
        current_conf: ??
        flim: ??
    """
    if len(sliced_traces) == 0:
        return None
    else:
        print(f"Number of sliced traces: {len(sliced_traces)}")

    if accumulation_range != None:
        if len(sliced_traces.shape) == 2:
            sliced_traces_trimmed = sliced_traces[0][
                accumulation_range[0] : accumulation_range[1]
            ]
        else:
            sliced_traces_trimmed = sliced_traces[
                accumulation_range[0] : accumulation_range[1]
            ]

    if plot:
        _, ax = plt.subplots(3, 1, figsize=(20, 10))
        t_space = np.arange(sliced_traces.shape[-1])
        if len(sliced_traces.shape) == 2:
            ax[0].plot(sliced_traces[0])
        else:
            ax[0].plot(sliced_traces)
        # ax[0].set_xlabel("time in µs")
        ax[0].set_xlabel("Fluxramp sample")
        ax[0].set_ylabel("amplitude in ADU")

        if accumulation_range != None:
            ax[0].axvline(accumulation_range[0], color="red")
            ax[0].axvline(accumulation_range[1], color="red")

        ax[1].plot(sliced_traces_trimmed)
        # ax[0].set_xlabel("time in µs")
        ax[1].set_xlabel("Fluxramp sample")
        ax[1].set_ylabel("amplitude in ADU")

    f_space, p_spec = ipe_scipy.normalized_fft(
        sliced_traces_trimmed, 1 / sample_rate, window
    )
    # FFT is averaged if 2d-array is passed

    if plot:
        ax[2].plot(1e-6 * f_space, p_spec)
        if height is None:
            print("Pass a height to specify the peak threshold")
        else:
            ax[2].semilogy(1e-6 * f_space, height * np.ones(len(f_space)))
        ax[2].set_xlim(flim)
        ax[2].set_xlabel("frequency in MHz")
        ax[2].set_ylabel("power spectral density")

        if not current_conf is None:
            plot_frequency_config(current_conf, ax[1])
        plt.show()

    peak_indices, _ = signal.find_peaks(p_spec, height=height)
    peak_freq = [f_space[idx] for idx in peak_indices]
    peak_ampl = p_spec[5]

    # print(f"Peak freq: {peak_freq[0]}, index {peak_indices[0]}")

    return sorted(peak_freq), peak_ampl


def plot_frequency_config(frequencies, ax):
    """
    Adds the frequency configuration onto a given plot
    """
    y_min, y_max = ax.get_ylim()
    for freq in frequencies:
        freq = freq * 1e-6  # display in MHz
        ax.plot([freq, freq], [y_min, y_max], color="g")


def slice_at_sync(raw_data, samples_per_ramp, add_sync_latency=1):
    """
    Slices raw data based on the sync signal encoded in the least significant bit (of real part)

    Args:
        raw_data : (int) data array with LSB representing the sync signal
        samples_per_ramp : sample count between two sync signals
        add_sync_latency : additional sync latency (e.g. due to windowing in hardware), defaults to 1

    Returns:
        numpy 2d-array of sliced data traces
    """
    sync_flags = np.nonzero(np.real(raw_data) % 2)[0] + add_sync_latency
    samples_per_ramp = int(round(samples_per_ramp))
    slice_count = len(raw_data) // samples_per_ramp - 1
    for idx, diff in enumerate(np.diff(sync_flags)):
        if diff != samples_per_ramp:
            print(
                f"Warning: Only {idx} / {slice_count} possible Slices used due to mismatch in Spacing. Diff should be {samples_per_ramp}, but is {diff}"
            )
            slice_count = idx
            break

    # avoid indexing errors
    if slice_count > len(sync_flags) - 1 or sync_flags[slice_count] >= len(raw_data):
        slice_count -= 1

    # output a numpy 2d-array
    return raw_data[sync_flags[0] : sync_flags[slice_count]].reshape(
        slice_count, samples_per_ramp
    )


def fit_modulation_frequencies(
    data,
    sample_rate,
    fit_width,
    peak_height,
    window="blackmanharris",
    flim=(0, None),
):
    """
    fit the spectral peaks to get the modulation/carrier frequencies

    Args:
        data          : bypassed raw data (real), sliced into a 2d-array
        sample_rate   : sample rate of the traces
        fit_width     : number of samples around the peak contributing to the fit
        peak_height   : threshold for find_peaks
        window        : window function used for the FFT

    Returns
        mu : the center frequencies of the fit
    """
    # Generate the Spectrum and find peaks
    f_space, p_spec = ipe_scipy.normalized_fft(data, 1 / sample_rate, window)
    peak_indices, _ = signal.find_peaks(
        p_spec, height=peak_height, distance=fit_width // 2
    )

    _, ax = plt.subplots(1, 1, figsize=(20, 10))
    ax.plot(f_space * 1e-6, p_spec, color="b")
    flim = ax.set_xlim(flim)
    ax.set_xlabel("frequency in MHz")
    ax.set_ylabel("spectral density (a. u.)")

    # Fit the gaussian function to each peak and save the parameters
    number_peaks = len(peak_indices)
    ampl = np.zeros(number_peaks)
    mu = np.zeros(number_peaks)
    sigma = np.zeros(number_peaks)

    x_space = np.linspace(flim[0], flim[1], 300)
    for j, peak_idx in enumerate(peak_indices):
        try:
            ampl[j], mu[j], sigma[j] = ipe_scipy.fit_gaussian(
                f_space, p_spec, peak_idx, fit_width
            )
        except RuntimeError:
            print(f"Fitting failed for Peak at {1e-6 * f_space[peak_idx]:.2f} MHz")
            ampl[j], mu[j], sigma[j] = np.nan, np.nan, np.nan
            continue

        ax.plot(
            x_space,
            ipe_scipy.gaussian(x_space * 1e6, ampl[j], mu[j], sigma[j]),
            color="r",
            alpha=0.5,
        )

    plt.show()

    return mu


def show_frequency_drift(
    sliced_traces,
    sample_rate,
    subframe_length,
    subframe_count,
    fit_width,
    peak_height,
    peak_count,
    window="blackmanharris",
):
    """
    Investigate the modulation/carrier frequencies in the time frame of one ramp.
    Use multiple traces for higher accurracy.
    The FFT is performed over multiple overlapping subframes, fitting the peaks for each time section.
    The relative change of modulation frequencies is plotted

    Args:
        sliced_traces   : bypassed raw data (real), sliced into a 2d-array
        sample_rate     : sample rate of raw data
        subframe_length : sample count of each subframe, must be smaller than length of a sliced trace
        subframe_count  : number of subframes
        fit_width       : number of samples around the peak contributing to the fit
        peak_height     : threshold for find_peaks
        peak_count      : number of carrier/modulation frequencies in the signal
        window          : window function used for the FFT
        debug           : plots the spectra to give an estimation on the peak_height
    """
    # Define subframe intervals
    half_frame = subframe_length // 2
    trace_length = sliced_traces.shape[-1]
    center_indices = np.linspace(
        half_frame, trace_length - half_frame, subframe_count, endpoint=True, dtype=int
    )

    # Initialize data and parameter arrays
    # p_spec_subframes = np.zeros((subframe_count, half_frame - 1))
    mod_frequencies = np.zeros((subframe_count, peak_count))

    # Prepare Plot
    _, ax = plt.subplots(1, 1, figsize=(20, 10))
    if peak_height is None:
        ax.set_xlabel("frequency in MHz")
        ax.set_ylabel("power spectral density in arb. units")
        colors = plt.get_cmap("inferno")(np.linspace(0, 1, subframe_count))
    else:
        ax.set_xlabel("center of subframe in timeframe of a flux ramp in µs")
        ax.set_ylabel("relative change of frequency")
        colors = plt.get_cmap("inferno")(
            np.linspace(0.1, 0.9, peak_count, endpoint=True)
        )
        frame_spacing = (center_indices[1] - center_indices[0]) / sample_rate
        dot_shift = frame_spacing / (peak_count + 1) / 2

    # Generate FFTs of subframes
    for j, c_idx in enumerate(center_indices):
        # f_space, p_spec_subframes[j] = ipe_scipy.normalized_fft(
        f_space, p_spec = ipe_scipy.normalized_fft(
            input_signal=window[:, c_idx - half_frame : c_idx + half_frame],
            d_t=1 / sample_rate,
            window_name=window,
        )

        if peak_height is None:
            ax.plot(f_space * 1e-6, p_spec, color=colors[j], label=f"subframe {j}")
            continue

        peak_indices, _ = signal.find_peaks(
            p_spec, height=peak_height, distance=fit_width // 2
        )
        for k, p_idx in enumerate(sorted(peak_indices)):
            try:
                _, mod_frequencies[j, k], sigma = ipe_scipy.fit_gaussian(
                    f_space, p_spec, p_idx, fit_width
                )
            except RuntimeError:
                print(
                    f"Fitting failed for peak at {f_space[p_idx] * 1e-6} MHz in subframe {j}"
                )
                mod_frequencies[j, k] = np.nan

            if j == 0:
                label = f"$f_0 = {mod_frequencies[j, k] * 1e-6}$ MHz"
            else:
                label = None

            # generate horizontally shifted errorbars
            ax.errorbar(
                x=(c_idx / sample_rate + dot_shift * (k - peak_count // 2)) * 1e6,
                y=mod_frequencies[j, k] / mod_frequencies[0][k],
                yerr=sigma / mod_frequencies[0][k],
                marker="o",
                color=colors[k],
                label=label,
            )

    plt.legend(loc="best")
    plt.show()
